language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update && sudo apt-get install systemd
# Based on:
# https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=${TRAVIS_PYTHON_VERSION%-dev}
  - source activate test-environment
  - conda install -c bioconda spades
  - python setup.py install
script:
  # Python unit tests
  - python -m unittest
  # Ensure the package execution via __main__.py works.
  - python -m umbra -h
  # Try full demo runs.
  - bash demo/demo_1.sh
  - bash demo/demo_2.sh
  # Ensure the installation process created a viable script for the entry
  # point.
  - umbra -h
  # Check the version argument.
  - umbra --version
  # Try a dry run installation.
  - sudo -E $(which umbra) --action install --dry-run
  # Try a live installation.
  - sudo -E $(which umbra) --action install
  - sudo systemctl start umbra
  - sudo systemctl status umbra
