"""
A simple interface to Box.com to upload individual files to a folder.

See BoxUploader for usage details.
"""

import re
import logging
import datetime
import subprocess
from pathlib import Path
import boxsdk
import yaml
from .util import yaml_load

class BoxUploader:
    """A simple Box API interface to upload files to one directory.

    Credentials are provided in a dedicated YAML-formatted text file that must
    at least contain client_id, client_secret, and redirect_uri entries.
    user_access_token and user_refresh_token are the time-limited credentials
    provided by Box.  They will be generated by a one-time web-based login if
    needed, but note that requires a manual step with a browser and read access
    to web server logs.  Once valid the credentials will be refreshed
    automatically and can last indefinitely as long as there's communication
    with Box at least every sixty days.  For more on the first-time credentials
    setup see _janky_auth_trick().

    Other options are provided by a configuration dictionary, currently just
    specifying the folder ID to upload to.  (This ID is the last segment of the
    URL shown in the web interface for any given folder; 0 for the root
    folder.)

    There is just one public function, upload(), taking a file path and an
    optional custom name.  An existing file with the same name in Box will
    cause an exception."""

    # These dict keys must appear in the credentials file.  user_access_token
    # and user_refresh_token can be missing.
    REQUIRED_FIELDS = ["client_id", "client_secret", "redirect_uri"]

    def __init__(self, creds_store_path, config):
        self.logger = logging.getLogger(__name__)
        self.config = config
        self.creds_store_path = Path(creds_store_path)
        self._init_creds()
        self._init_upload_folder()
        self.logger.debug("BoxUploader initialized.")

    def _init_creds(self):
        """Load Box API credentials and put in an OAuth2 object.

        If authentication fails or credentials are missing, attempt to
        re-connect with Box in a browser with a provided URL."""
        self._load_creds()
        try:
            self._init_client()
        except boxsdk.exception.BoxAPIException as e:
            # If (and only if) the problem is authentication, try getting new
            # access and refresh tokens.
            if e.status == 400 and not self.config.get("strict_auth"):
                msg = "Authentication failure.  Try re-connecting with Box in"
                msg += " a browser with the URL shown."
                self.logger.critical(msg)
                self._janky_auth_trick()
            else:
                raise e

    def _load_creds(self):
        self.creds = yaml_load(self.creds_store_path)
        req = BoxUploader.REQUIRED_FIELDS
        miss = [field for field in req if field not in self.creds.keys()]
        if miss:
            raise ValueError("Missing configuration entries: %s" % ", ".join(miss))
        for key in ["user_access_token", "user_refresh_token"]:
            self.creds[key] = self.creds.get(key, 0)

    def _init_client(self):
        self.oauth = boxsdk.OAuth2(
            client_id=self.creds["client_id"],
            client_secret=self.creds["client_secret"],
            store_tokens=self._store_tokens,
            access_token=self.creds["user_access_token"],
            refresh_token=self.creds["user_refresh_token"])
        self.client = boxsdk.Client(self.oauth)
        me = self.client.user(user_id='me').get()
        self.max_upload_size = int(me["max_upload_size"])
        self.logger.info('User: %s' % me['login'])
        self.logger.info('Max upload size in bytes: %d' % self.max_upload_size)

    def _init_upload_folder(self):
        folder_id = self.config.get("folder_id", 0)
        self.folder = self.client.folder(folder_id)
        name = self.folder.get()['name']
        msg = "Upload folder: %d (%s)" % (folder_id, name)
        self.logger.info(msg)

    def _store_tokens(self, access_token, refresh_token):
        """Callback to store new access/refresh tokens to disk."""
        self.creds["user_access_token"] = access_token
        self.creds["user_refresh_token"] = refresh_token
        with open(self.creds_store_path, "w") as f:
            f.write(yaml.dump(self.creds))
        self.logger.info("Tokens refreshed.")

    def upload(self, path, name=None):
        """Upload file from a given path, optionally with custom name."""
        path = Path(path)
        fsize = path.stat().st_size
        if fsize > self.max_upload_size:
            msg = "File size (%d) exceeds max upload size (%d)"
            msg += msg % (fsize, self.max_upload_size)
            raise ValueError(msg)
        if not name:
            name = path.name
        # Possibly add a call to folder.canUpload() to make sure it would work,
        # first.
        box_file = self.folder.upload(str(path), name)
        url = box_file.get_shared_link_download_url(access="open")
        self.logger.info("File uploaded: %s" % str(path))
        return url

    def _list(self, chunk=100):
        """List of file and folder objects in the uploader folder."""
        offset = 0
        items = self.folder.get_items(chunk)
        allitems = items
        while len(items) == chunk:
            offset += chunk
            items = self.folder.get_items(chunk, offset)
            allitems.extend(items)
        return allitems

    def _janky_auth_trick(self, log_path="/var/log/nginx/access.log"):
        """The most minimal sort of method of getting a Box API access token.

        Steps:
        1) set up App on box.com, pointing the redirect URL to your own web server
        2) run this function
        3) take app auth URL from standard output
        4) visit app auth URL in browser, triggering Box to contact your server
        5) take OAuth2 object as return value and/or auth text from standard output

        log_path should be the path to a readable web server log file in the Common
        Log Format.

        In more detail:

        1) First create an App at https://app.box.com/developers/console.  For
        Authentication Method use "Standard OAuth 2.0 (User Authentication)"
        Copy and paste the Client ID and Client Secret text into the
        credeitnals file.  Set Redirect URI to a HTTPS URL you control.  The
        destination doesn't much matter since it can just trigger a 404 error
        on your side that shows up in the log.  You must have control over an
        HTTPS-enabled web server to do this; I originally planned to use netcat
        on a high-numbered port and just read the text, but Box requires HTTPS.
        (All this, even though using the API doesn't actually require a web
        server running.)

        2) Now run this function and note the URL printed.

        3) Nothing much will happen at first.  Copy and paste the URL printed to
        standard output into a web browser.

        4) Say "yes" in the browser to give the app access to your account, and
        then watch for more lines on the terminal.  Box should connect, make an
        HTTP request with all the relevant info, and trigger a 404 error that ends
        up in the logs.  (There's a pretty short timeout -- sixty seconds? -- on
        the whole process, so as soon as Box sends the data to your web server this
        function needs to catch it.)

        5) Use the returned OAuth2 object and/or enter those extra lines into
        config.py as user_access_token and user_refresh_token.
        """
        self.oauth = boxsdk.OAuth2(client_id=self.creds["client_id"],
                                   client_secret=self.creds["client_secret"])
        auth_url = self.oauth.get_authorization_url(self.creds["redirect_uri"])[0]
        self.logger.critical("Auth URL: " + auth_url)
        code = scrape_log_for_code(log_path)
        access_token, refresh_token = self.oauth.authenticate(code)
        self._store_tokens(access_token, refresh_token)
        self._init_client()

def _parse_log_line(line):
    """Parse a single line of log file text assuming Common Log Format."""
    # Nginx:
    #log_format combined '$remote_addr - $remote_user [$time_local] '
    #                    '"$request" $status $body_bytes_sent '
    #                    '"$http_referer" "$http_user_agent"';
    # See also:
    # https://nginx.org/en/docs/http/ngx_http_log_module.html
    # https://en.wikipedia.org/wiki/Common_Log_Format
    try:
        line = line.decode("ASCII")
    except AttributeError:
        pass
    #       src IP   X  user   time    request  status   bytes     referer   agent
    fmt = r'([0-9.]+) - (.+) \[(.+)\] "([^"]+)" ([0-9]+) ([0-9]+) "([^"]+)" "([^"]+)"'
    fmt_date = "%d/%b/%Y:%H:%M:%S %z"
    m = re.match(fmt, line)
    logentry = {}
    logentry["IP"] = m.group(1)
    logentry["User"] = m.group(2)
    logentry["Time"] = datetime.datetime.strptime(m.group(3), fmt_date)
    logentry["Request"] = m.group(4)
    logentry["Status"] = m.group(5)
    logentry["Bytes"] = int(m.group(6))
    logentry["Referer"] = m.group(7)
    logentry["User Agent"] = m.group(8)
    return logentry

def scrape_log_for_code(log_path):
    """Watch log file until a Box auth code appears, then return it."""
    box_url_suffix = 'box.com/api/oauth2/authorize'
    # "tail -n 0 -f" will give all lines written to the file after the tail
    # process starts.
    # Based on: https://stackoverflow.com/a/12523371/6073858
    f = subprocess.Popen(['tail', '-n', '0', '-f', log_path],
                         stdout=subprocess.PIPE)
    while True:
        line = f.stdout.readline()
        logentry = _parse_log_line(line)
        if box_url_suffix in logentry["Referer"]:
            m = re.search('code=([^ ]*) ', logentry["Request"])
            code = m.group(1)
            return code
