version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m unittest
          name: Test
      - run:
          command: python -m umbra -h
          name: Test command line interface
      - run:
          command: bash demo/demo_1.sh
          name: Test demo 1
      - run:
          command: bash demo/demo_2.sh
          name: Test demo 2
      - run:
          command: umbra -h
          name: Test installed command line interface
      - run:
          command: umbra --version
          name: Test version argument
      - run:
          command: sudo -E $(which umbra) --action install --dry-run
          name: Test dry run installation
      - run:
          command: sudo -E $(which umbra) --action install
          name: Install
      - run:
          command: sudo systemctl start umbra
          name: Start service
      - run:
          command: sudo systemctl status umbra
          name: Check service

workflows:
  main:
    jobs:
      - build-and-test
