# https://circleci.com/docs/2.0/language-python/
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/executor-intro/
# https://circleci.com/docs/2.0/sample-config/
version: 2.1

jobs:
  main:
    docker:
      - image: cimg/base:2020.01
    steps:
      # Initial setup
      - checkout
      - restore_cache:
          keys:
            - conda-env-{{ checksum "setup.py" }}
      - run:
          name: Set up conda environemnt
          working_directory: ..
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda create -q -n test-environment -c bioconda spades python=3.7
      - save_cache:
          key: conda-env-{{ checksum "setup.py" }}
      - run:
          name: Check conda environment
          command: ~/miniconda/bin/conda list -n test-environment
      # Python package install
      - run:
          name: Install Python package
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            source activate test-environment
            python setup.py install
      # Python package tests
      - run:
          name: Unit tests
          command: python -m unittest
      - run:
          name: Test command line interface
          command: python -m umbra -h
      - run:
          name: Test demo 1
          command: bash demo/demo_1.sh
      - run:
          name: Test demo 2
          command: bash demo/demo_2.sh
      - run:
          name: Test installed command line interface
          command: umbra -h
      - run:
          name: Test version argument
          command: umbra --version
      # OS install
      - run:
          name: Test dry run installation
          command: sudo -E $HOME/miniconda/bin/umbra --action install --dry-run
      - run:
          name: Install
          command: sudo -E $HOME/miniconda/bin/umbra --action install
      - run:
          name: Start service
          command: sudo systemctl start umbra
      - run:
          name: Check service
          command: sudo systemctl status umbra

workflows:
  main:
    jobs:
      - main
